---
deployment:
  tasks: 
    - export REPOPATH=/home/a7890by/repositories/kivi-ride.by/*
    - export SITEPATH=/home/a7890by/kivi-ride.by/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH